// Generated by CoffeeScript 1.8.0
(function() {
  "use strict";
  var fs, lp, path, request;

  path = require("path");

  fs = require("fs");

  request = require("superagent");

  lp = function(bug_id, cb) {
    var api_url;
    api_url = "https://api.launchpad.net/1.0/bugs/" + bug_id;
    return request.get(api_url).end(cb);
  };

  module.exports = lp;

}).call(this);
